export const states = [
  {
    name: "Abia",
    localGovts: [
      { lga: "Aba North" },
      { lga: "Aba South" },
      { lga: "Arochukwu" },
      { lga: "Bende" },
      { lga: "Ikwuano" },
      { lga: "Isiala Ngwa North" },
      { lga: "Isiala Ngwa South" },
      { lga: "Isuikwuato" },
      { lga: "Obi Ngwa" },
      { lga: "Ohafia" },
      { lga: "Osisioma" },
      { lga: "Ugwunagbo" },
      { lga: "Ukwa East" },
      { lga: "Ukwa West" },
      { lga: "Umuahia North" },
      { lga: "Umuahia South" },
      { lga: "Umu Nneochi" },
    ],
  },
  {
    name: "Adamawa",
    localGovts: [
      { lga: "Demsa" },
      { lga: "Fufure" },
      { lga: "Ganye" },
      { lga: "Gayuk" },
      { lga: "Gombi" },
      { lga: "Grie" },
      { lga: "Hong" },
      { lga: "Jada" },
      { lga: "Larmurde" },
      { lga: "Madagali" },
      { lga: "Maiha" },
      { lga: "Mayo Belwa" },
      { lga: "Michika" },
      { lga: "Mubi North" },
      { lga: "Mubi South" },
      { lga: "Numan" },
      { lga: "Shelleng" },
      { lga: "Song" },
      { lga: "Toungo" },
      { lga: "Yola North" },
      { lga: "Yola South" },
    ],
  },
  {
    name: "AkwaIbom",
    localGovts: [
      { lga: "Abak" },
      { lga: "Eastern Obolo" },
      { lga: "Eket" },
      { lga: "Esit Eket" },
      { lga: "Essien Udim" },
      { lga: "Etim Ekpo" },
      { lga: "Etinan" },
      { lga: "Ibeno" },
      { lga: "Ibesikpo Asutan" },
      { lga: "Ibiono-Ibom" },
      { lga: "Ika" },
      { lga: "Ikono" },
      { lga: "Ikot Abasi" },
      { lga: "Ikot Ekpene" },
      { lga: "Ini" },
      { lga: "Itu" },
      { lga: "Mbo" },
      { lga: "Mkpat-Enin" },
      { lga: "Nsit-Atai" },
      { lga: "Nsit-Ibom" },
      { lga: "Nsit-Ubium" },
      { lga: "Obot Akara" },
      { lga: "Okobo" },
      { lga: "Onna" },
      { lga: "Oron" },
      { lga: "Oruk Anam" },
      { lga: "Udung-Uko" },
      { lga: "Ukanafun" },
      { lga: "Uruan" },
      { lga: "Urue-Offong Oruko" },
      { lga: "Uyo" },
    ],
  },
  {
    name: "Anambra",
    localGovts: [
      { lga: "Aguata" },
      { lga: "Anambra East" },
      { lga: "Anambra West" },
      { lga: "Anaocha" },
      { lga: "Awka North" },
      { lga: "Awka South" },
      { lga: "Ayamelum" },
      { lga: "Dunukofia" },
      { lga: "Ekwusigo" },
      { lga: "Idemili North" },
      { lga: "Idemili South" },
      { lga: "Ihiala" },
      { lga: "Njikoka" },
      { lga: "Nnewi North" },
      { lga: "Nnewi South" },
      { lga: "Ogbaru" },
      { lga: "Onitsha North" },
      { lga: "Onitsha South" },
      { lga: "Orumba North" },
      { lga: "Orumba South" },
      { lga: "Oyi" },
    ],
  },
  {
    name: "Bauchi",
    localGovts: [
      { lga: "Alkaleri" },
      { lga: "Bauchi" },
      { lga: "Bogoro" },
      { lga: "Damban" },
      { lga: "Darazo" },
      { lga: "Dass" },
      { lga: "Gamawa" },
      { lga: "Ganjuwa" },
      { lga: "Giade" },
      { lga: "Itas-Gadau" },
      { lga: "Jama are" },
      { lga: "Katagum" },
      { lga: "Kirfi" },
      { lga: "Misau" },
      { lga: "Ningi" },
      { lga: "Shira" },
      { lga: "Tafawa Balewa" },
      { lga: "Toro" },
      { lga: "Warji" },
      { lga: "Zaki" },
    ],
  },
  {
    name: "Bayelsa",
    localGovts: [
      { lga: "Brass" },
      { lga: "Ekeremor" },
      { lga: "Kolokuma Opokuma" },
      { lga: "Nembe" },
      { lga: "Ogbia" },
      { lga: "Sagbama" },
      { lga: "Southern Ijaw" },
      { lga: "Yenagoa" },
    ],
  },
  {
    name: "Benue",
    localGovts: [
      { lga: "Agatu" },
      { lga: "Apa" },
      { lga: "Ado" },
      { lga: "Buruku" },
      { lga: "Gboko" },
      { lga: "Guma" },
      { lga: "Gwer East" },
      { lga: "Gwer West" },
      { lga: "Katsina-Ala" },
      { lga: "Konshisha" },
      { lga: "Kwande" },
      { lga: "Logo" },
      { lga: "Makurdi" },
      { lga: "Obi" },
      { lga: "Ogbadibo" },
      { lga: "Ohimini" },
      { lga: "Oju" },
      { lga: "Okpokwu" },
      { lga: "Oturkpo" },
      { lga: "Tarka" },
      { lga: "Ukum" },
      { lga: "Ushongo" },
      { lga: "Vandeikya" },
    ],
  },
  {
    name: "Borno",
    localGovts: [
      { lga: "Abadam" },
      { lga: "Askira-Uba" },
      { lga: "Bama" },
      { lga: "Bayo" },
      { lga: "Biu" },
      { lga: "Chibok" },
      { lga: "Damboa" },
      { lga: "Dikwa" },
      { lga: "Gubio" },
      { lga: "Guzamala" },
      { lga: "Gwoza" },
      { lga: "Hawul" },
      { lga: "Jere" },
      { lga: "Kaga" },
      { lga: "Kala-Balge" },
      { lga: "Konduga" },
      { lga: "Kukawa" },
      { lga: "Kwaya Kusar" },
      { lga: "Mafa" },
      { lga: "Magumeri" },
      { lga: "Maiduguri" },
      { lga: "Marte" },
      { lga: "Mobbar" },
      { lga: "Monguno" },
      { lga: "Ngala" },
      { lga: "Nganzai" },
      { lga: "Shani" },
    ],
  },
  {
    name: "Cross River",
    localGovts: [
      { lga: "Abi" },
      { lga: "Akamkpa" },
      { lga: "Akpabuyo" },
      { lga: "Bakassi" },
      { lga: "Bekwarra" },
      { lga: "Biase" },
      { lga: "Boki" },
      { lga: "Calabar Municipal" },
      { lga: "Calabar South" },
      { lga: "Etung" },
      { lga: "Ikom" },
      { lga: "Obanliku" },
      { lga: "Obubra" },
      { lga: "Obudu" },
      { lga: "Odukpani" },
      { lga: "Ogoja" },
      { lga: "Yakuur" },
      { lga: "Yala" },
    ],
  },
  {
    name: "Delta",
    localGovts: [
      { lga: "Aniocha North" },
      { lga: "Aniocha South" },
      { lga: "Bomadi" },
      { lga: "Burutu" },
      { lga: "Ethiope East" },
      { lga: "Ethiope West" },
      { lga: "Ika North East" },
      { lga: "Ika South" },
      { lga: "Isoko North" },
      { lga: "Isoko South" },
      { lga: "Ndokwa East" },
      { lga: "Ndokwa West" },
      { lga: "Okpe" },
      { lga: "Oshimili North" },
      { lga: "Oshimili South" },
      { lga: "Patani" },
      { lga: "Sapele" },
      { lga: "Udu" },
      { lga: "Ughelli North" },
      { lga: "Ughelli South" },
      { lga: "Ukwuani" },
      { lga: "Uvwie" },
      { lga: "Warri North" },
      { lga: "Warri South" },
      { lga: "Warri South West" },
    ],
  },
  {
    name: "Ebonyi",
    localGovts: [
      { lga: "Abakaliki" },
      { lga: "Afikpo North" },
      { lga: "Afikpo South" },
      { lga: "Ebonyi" },
      { lga: "Ezza North" },
      { lga: "Ezza South" },
      { lga: "Ikwo" },
      { lga: "Ishielu" },
      { lga: "Ivo" },
      { lga: "Izzi" },
      { lga: "Ohaozara" },
      { lga: "Ohaukwu" },
      { lga: "Onicha" },
    ],
  },
  {
    name: "Edo",
    localGovts: [
      { lga: "Akoko-Edo" },
      { lga: "Egor" },
      { lga: "Esan Central" },
      { lga: "Esan North-East" },
      { lga: "Esan South-East" },
      { lga: "Esan West" },
      { lga: "Etsako Central" },
      { lga: "Etsako East" },
      { lga: "Etsako West" },
      { lga: "Igueben" },
      { lga: "Ikpoba Okha" },
      { lga: "Orhionmwon" },
      { lga: "Oredo" },
      { lga: "Ovia North-East" },
      { lga: "Ovia South-West" },
      { lga: "Owan East" },
      { lga: "Owan West" },
      { lga: "Uhunmwonde" },
    ],
  },
  {
    name: "Ekiti",
    localGovts: [
      { lga: "Ado Ekiti" },
      { lga: "Efon" },
      { lga: "Ekiti East" },
      { lga: "Ekiti South-West" },
      { lga: "Ekiti West" },
      { lga: "Emure" },
      { lga: "Gbonyin" },
      { lga: "Ido Osi" },
      { lga: "Ijero" },
      { lga: "Ikere" },
      { lga: "Ikole" },
      { lga: "Ilejemeje" },
      { lga: "Irepodun-Ifelodun" },
      { lga: "Ise-Orun" },
      { lga: "Moba" },
      { lga: "Oye" },
    ],
  },
  {
    name: "Rivers",
    localGovts: [
      { lga: "Port Harcourt" },
      { lga: "Obio-Akpor" },
      { lga: "Okrika" },
      { lga: "Ogu–Bolo" },
      { lga: "Eleme" },
      { lga: "Tai" },
      { lga: "Gokana" },
      { lga: "Khana" },
      { lga: "Oyigbo" },
      { lga: "Opobo–Nkoro" },
      { lga: "Andoni" },
      { lga: "Bonny" },
      { lga: "Degema" },
      { lga: "Asari-Toru" },
      { lga: "Akuku-Toru" },
      { lga: "Abua–Odual" },
      { lga: "Ahoada West" },
      { lga: "Ahoada East" },
      { lga: "Ogba–Egbema–Ndoni" },
      { lga: "Emohua" },
      { lga: "Ikwerre" },
      { lga: "Etche" },
      { lga: "Omuma" },
    ],
  },
  {
    name: "Enugu",
    localGovts: [
      { lga: "Aninri" },
      { lga: "Awgu" },
      { lga: "Enugu East" },
      { lga: "Enugu North" },
      { lga: "Enugu South" },
      { lga: "Ezeagu" },
      { lga: "Igbo Etiti" },
      { lga: "Igbo Eze North" },
      { lga: "Igbo Eze South" },
      { lga: "Isi Uzo" },
      { lga: "Nkanu East" },
      { lga: "Nkanu West" },
      { lga: "Nsukka" },
      { lga: "Oji River" },
      { lga: "Udenu" },
      { lga: "Udi" },
      { lga: "Uzo Uwani" },
    ],
  },
  {
    name: "FCT",
    localGovts: [
      { lga: "Abaji" },
      { lga: "Bwari" },
      { lga: "Gwagwalada" },
      { lga: "Kuje" },
      { lga: "Kwali" },
      { lga: "Municipal Area Council" },
    ],
  },
  {
    name: "Gombe",
    localGovts: [
      { lga: "Akko" },
      { lga: "Balanga" },
      { lga: "Billiri" },
      { lga: "Dukku" },
      { lga: "Funakaye" },
      { lga: "Gombe" },
      { lga: "Kaltungo" },
      { lga: "Kwami" },
      { lga: "Nafada" },
      { lga: "Shongom" },
      { lga: "Yamaltu-Deba" },
    ],
  },
  {
    name: "Imo",
    localGovts: [
      { lga: "Aboh Mbaise" },
      { lga: "Ahiazu Mbaise" },
      { lga: "Ehime Mbano" },
      { lga: "Ezinihitte" },
      { lga: "Ideato North" },
      { lga: "Ideato South" },
      { lga: "Ihitte-Uboma" },
      { lga: "Ikeduru" },
      { lga: "Isiala Mbano" },
      { lga: "Isu" },
      { lga: "Mbaitoli" },
      { lga: "Ngor Okpala" },
      { lga: "Njaba" },
      { lga: "Nkwerre" },
      { lga: "Nwangele" },
      { lga: "Obowo" },
      { lga: "Oguta" },
      { lga: "Ohaji-Egbema" },
      { lga: "Okigwe" },
      { lga: "Orlu" },
      { lga: "Orsu" },
      { lga: "Oru East" },
      { lga: "Oru West" },
      { lga: "Owerri Municipal" },
      { lga: "Owerri North" },
      { lga: "Owerri West" },
      { lga: "Unuimo" },
    ],
  },
  {
    name: "Jigawa",
    localGovts: [
      { lga: "Auyo" },
      { lga: "Babura" },
      { lga: "Biriniwa" },
      { lga: "Birnin Kudu" },
      { lga: "Buji" },
      { lga: "Dutse" },
      { lga: "Gagarawa" },
      { lga: "Garki" },
      { lga: "Gumel" },
      { lga: "Guri" },
      { lga: "Gwaram" },
      { lga: "Gwiwa" },
      { lga: "Hadejia" },
      { lga: "Jahun" },
      { lga: "Kafin Hausa" },
      { lga: "Kazaure" },
      { lga: "Kiri Kasama" },
      { lga: "Kiyawa" },
      { lga: "Kaugama" },
      { lga: "Maigatari" },
      { lga: "Malam Madori" },
      { lga: "Miga" },
      { lga: "Ringim" },
      { lga: "Roni" },
      { lga: "Sule Tankarkar" },
      { lga: "Taura" },
      { lga: "Yankwashi" },
    ],
  },
  {
    name: "Kaduna",
    localGovts: [
      { lga: "Birnin Gwari" },
      { lga: "Chikun" },
      { lga: "Giwa" },
      { lga: "Igabi" },
      { lga: "Ikara" },
      { lga: "Jaba" },
      { lga: "Jema a" },
      { lga: "Kachia" },
      { lga: "Kaduna North" },
      { lga: "Kaduna South" },
      { lga: "Kagarko" },
      { lga: "Kajuru" },
      { lga: "Kaura" },
      { lga: "Kauru" },
      { lga: "Kubau" },
      { lga: "Kudan" },
      { lga: "Lere" },
      { lga: "Makarfi" },
      { lga: "Sabon Gari" },
      { lga: "Sanga" },
      { lga: "Soba" },
      { lga: "Zangon Kataf" },
      { lga: "Zaria" },
    ],
  },
  {
    name: "Kano",
    localGovts: [
      { lga: "Ajingi" },
      { lga: "Albasu" },
      { lga: "Bagwai" },
      { lga: "Bebeji" },
      { lga: "Bichi" },
      { lga: "Bunkure" },
      { lga: "Dala" },
      { lga: "Dambatta" },
      { lga: "Dawakin Kudu" },
      { lga: "Dawakin Tofa" },
      { lga: "Doguwa" },
      { lga: "Fagge" },
      { lga: "Gabasawa" },
      { lga: "Garko" },
      { lga: "Garun Mallam" },
      { lga: "Gaya" },
      { lga: "Gezawa" },
      { lga: "Gwale" },
      { lga: "Gwarzo" },
      { lga: "Kabo" },
      { lga: "Kano Municipal" },
      { lga: "Karaye" },
      { lga: "Kibiya" },
      { lga: "Kiru" },
      { lga: "Kumbotso" },
      { lga: "Kunchi" },
      { lga: "Kura" },
      { lga: "Madobi" },
      { lga: "Makoda" },
      { lga: "Minjibir" },
      { lga: "Nasarawa" },
      { lga: "Rano" },
      { lga: "Rimin Gado" },
      { lga: "Rogo" },
      { lga: "Shanono" },
      { lga: "Sumaila" },
      { lga: "Takai" },
      { lga: "Tarauni" },
      { lga: "Tofa" },
      { lga: "Tsanyawa" },
      { lga: "Tudun Wada" },
      { lga: "Ungogo" },
      { lga: "Warawa" },
      { lga: "Wudil" },
    ],
  },
  {
    name: "Katsina",
    localGovts: [
      { lga: "Bakori" },
      { lga: "Batagarawa" },
      { lga: "Batsari" },
      { lga: "Baure" },
      { lga: "Bindawa" },
      { lga: "Charanchi" },
      { lga: "Dandume" },
      { lga: "Danja" },
      { lga: "Dan Musa" },
      { lga: "Daura" },
      { lga: "Dutsi" },
      { lga: "Dutsin Ma" },
      { lga: "Faskari" },
      { lga: "Funtua" },
      { lga: "Ingawa" },
      { lga: "Jibia" },
      { lga: "Kafur" },
      { lga: "Kaita" },
      { lga: "Kankara" },
      { lga: "Kankia" },
      { lga: "Katsina" },
      { lga: "Kurfi" },
      { lga: "Kusada" },
      { lga: "Mai Adua" },
      { lga: "Malumfashi" },
      { lga: "Mani" },
      { lga: "Mashi" },
      { lga: "Matazu" },
      { lga: "Musawa" },
      { lga: "Rimi" },
      { lga: "Sabuwa" },
      { lga: "Safana" },
      { lga: "Sandamu" },
      { lga: "Zango" },
    ],
  },
  {
    name: "Kebbi",
    localGovts: [
      { lga: "Aleiro" },
      { lga: "Arewa Dandi" },
      { lga: "Argungu" },
      { lga: "Augie" },
      { lga: "Bagudo" },
      { lga: "Birnin Kebbi" },
      { lga: "Bunza" },
      { lga: "Dandi" },
      { lga: "Fakai" },
      { lga: "Gwandu" },
      { lga: "Jega" },
      { lga: "Kalgo" },
      { lga: "Koko Besse" },
      { lga: "Maiyama" },
      { lga: "Ngaski" },
      { lga: "Sakaba" },
      { lga: "Shanga" },
      { lga: "Suru" },
      { lga: "Wasagu Danko" },
      { lga: "Yauri" },
      { lga: "Zuru" },
    ],
  },
  {
    name: "Kogi",
    localGovts: [
      { lga: "Adavi" },
      { lga: "Ajaokuta" },
      { lga: "Ankpa" },
      { lga: "Bassa" },
      { lga: "Dekina" },
      { lga: "Ibaji" },
      { lga: "Idah" },
      { lga: "Igalamela Odolu" },
      { lga: "Ijumu" },
      { lga: "Kabba Bunu" },
      { lga: "Kogi" },
      { lga: "Lokoja" },
      { lga: "Mopa Muro" },
      { lga: "Ofu" },
      { lga: "Ogori Magongo" },
      { lga: "Okehi" },
      { lga: "Okene" },
      { lga: "Olamaboro" },
      { lga: "Omala" },
      { lga: "Yagba East" },
      { lga: "Yagba West" },
    ],
  },
  {
    name: "Kwara",
    localGovts: [
      { lga: "Asa" },
      { lga: "Baruten" },
      { lga: "Edu" },
      { lga: "Ekiti" },
      { lga: "Ifelodun" },
      { lga: "Ilorin East" },
      { lga: "Ilorin South" },
      { lga: "Ilorin West" },
      { lga: "Irepodun" },
      { lga: "Isin" },
      { lga: "Kaiama" },
      { lga: "Moro" },
      { lga: "Offa" },
      { lga: "Oke Ero" },
      { lga: "Oyun" },
      { lga: "Pategi" },
    ],
  },
  {
    name: "Lagos",
    localGovts: [
      { lga: "Agege" },
      { lga: "Ajeromi-Ifelodun" },
      { lga: "Alimosho" },
      { lga: "Amuwo-Odofin" },
      { lga: "Apapa" },
      { lga: "Badagry" },
      { lga: "Epe" },
      { lga: "Eti Osa" },
      { lga: "Ibeju-Lekki" },
      { lga: "Ifako-Ijaiye" },
      { lga: "Ikeja" },
      { lga: "Ikorodu" },
      { lga: "Kosofe" },
      { lga: "Lagos Island" },
      { lga: "Lagos Mainland" },
      { lga: "Mushin" },
      { lga: "Ojo" },
      { lga: "Oshodi-Isolo" },
      { lga: "Shomolu" },
      { lga: "Surulere" },
    ],
  },
  {
    name: "Nasarawa",
    localGovts: [
      { lga: "Akwanga" },
      { lga: "Awe" },
      { lga: "Doma" },
      { lga: "Karu" },
      { lga: "Keana" },
      { lga: "Keffi" },
      { lga: "Kokona" },
      { lga: "Lafia" },
      { lga: "Nasarawa" },
      { lga: "Nasarawa Egon" },
      { lga: "Obi" },
      { lga: "Toto" },
      { lga: "Wamba" },
    ],
  },
  {
    name: "Niger",
    localGovts: [
      { lga: "Agaie" },
      { lga: "Agwara" },
      { lga: "Bida" },
      { lga: "Borgu" },
      { lga: "Bosso" },
      { lga: "Chanchaga" },
      { lga: "Edati" },
      { lga: "Gbako" },
      { lga: "Gurara" },
      { lga: "Katcha" },
      { lga: "Kontagora" },
      { lga: "Lapai" },
      { lga: "Lavun" },
      { lga: "Magama" },
      { lga: "Mariga" },
      { lga: "Mashegu" },
      { lga: "Mokwa" },
      { lga: "Moya" },
      { lga: "Paikoro" },
      { lga: "Rafi" },
      { lga: "Rijau" },
      { lga: "Shiroro" },
      { lga: "Suleja" },
      { lga: "Tafa" },
      { lga: "Wushishi" },
    ],
  },
  {
    name: "Ogun",
    localGovts: [
      { lga: "Abeokuta North" },
      { lga: "Abeokuta South" },
      { lga: "Ado-Odo Ota" },
      { lga: "Egbado North" },
      { lga: "Egbado South" },
      { lga: "Ewekoro" },
      { lga: "Ifo" },
      { lga: "Ijebu East" },
      { lga: "Ijebu North" },
      { lga: "Ijebu North East" },
      { lga: "Ijebu Ode" },
      { lga: "Ikenne" },
      { lga: "Imeko Afon" },
      { lga: "Ipokia" },
      { lga: "Obafemi Owode" },
      { lga: "Odeda" },
      { lga: "Odogbolu" },
      { lga: "Ogun Waterside" },
      { lga: "Remo North" },
      { lga: "Shagamu" },
    ],
  },
  {
    name: "Ondo",
    localGovts: [
      { lga: "Akoko North-East" },
      { lga: "Akoko North-West" },
      { lga: "Akoko South-West" },
      { lga: "Akoko South-East" },
      { lga: "Akure North" },
      { lga: "Akure South" },
      { lga: "Ese Odo" },
      { lga: "Idanre" },
      { lga: "Ifedore" },
      { lga: "Ilaje" },
      { lga: "Ile Oluji-Okeigbo" },
      { lga: "Irele" },
      { lga: "Odigbo" },
      { lga: "Okitipupa" },
      { lga: "Ondo East" },
      { lga: "Ondo West" },
      { lga: "Ose" },
      { lga: "Owo" },
    ],
  },
  {
    name: "Osun",
    localGovts: [
      { lga: "Atakunmosa East" },
      { lga: "Atakunmosa West" },
      { lga: "Aiyedaade" },
      { lga: "Aiyedire" },
      { lga: "Boluwaduro" },
      { lga: "Boripe" },
      { lga: "Ede North" },
      { lga: "Ede South" },
      { lga: "Ife Central" },
      { lga: "Ife East" },
      { lga: "Ife North" },
      { lga: "Ife South" },
      { lga: "Egbedore" },
      { lga: "Ejigbo" },
      { lga: "Ifedayo" },
      { lga: "Ifelodun" },
      { lga: "Ila" },
      { lga: "Ilesa East" },
      { lga: "Ilesa West" },
      { lga: "Irepodun" },
      { lga: "Irewole" },
      { lga: "Isokan" },
      { lga: "Iwo" },
      { lga: "Obokun" },
      { lga: "Odo Otin" },
      { lga: "Ola Oluwa" },
      { lga: "Olorunda" },
      { lga: "Oriade" },
      { lga: "Orolu" },
      { lga: "Osogbo" },
    ],
  },
  {
    name: "Oyo",
    localGovts: [
      { lga: "Afijio" },
      { lga: "Akinyele" },
      { lga: "Atiba" },
      { lga: "Atisbo" },
      { lga: "Egbeda" },
      { lga: "Ibadan North" },
      { lga: "Ibadan North-East" },
      { lga: "Ibadan North-West" },
      { lga: "Ibadan South-East" },
      { lga: "Ibadan South-West" },
      { lga: "Ibarapa Central" },
      { lga: "Ibarapa East" },
      { lga: "Ibarapa North" },
      { lga: "Ido" },
      { lga: "Irepo" },
      { lga: "Iseyin" },
      { lga: "Itesiwaju" },
      { lga: "Iwajowa" },
      { lga: "Kajola" },
      { lga: "Lagelu" },
      { lga: "Ogbomosho North" },
      { lga: "Ogbomosho South" },
      { lga: "Ogo Oluwa" },
      { lga: "Olorunsogo" },
      { lga: "Oluyole" },
      { lga: "Ona Ara" },
      { lga: "Orelope" },
      { lga: "Ori Ire" },
      { lga: "Oyo" },
      { lga: "Oyo East" },
      { lga: "Saki East" },
      { lga: "Saki West" },
      { lga: "Surulere" },
    ],
  },
  {
    name: "Plateau",
    localGovts: [
      { lga: "Bokkos" },
      { lga: "Barkin Ladi" },
      { lga: "Bassa" },
      { lga: "Jos East" },
      { lga: "Jos North" },
      { lga: "Jos South" },
      { lga: "Kanam" },
      { lga: "Kanke" },
      { lga: "Langtang South" },
      { lga: "Langtang North" },
      { lga: "Mangu" },
      { lga: "Mikang" },
      { lga: "Pankshin" },
      { lga: "Qua an Pan" },
      { lga: "Riyom" },
      { lga: "Shendam" },
      { lga: "Wase" },
    ],
  },
  {
    name: "Sokoto",
    localGovts: [
      { lga: "Binji" },
      { lga: "Bodinga" },
      { lga: "Dange Shuni" },
      { lga: "Gada" },
      { lga: "Goronyo" },
      { lga: "Gudu" },
      { lga: "Gwadabawa" },
      { lga: "Illela" },
      { lga: "Isa" },
      { lga: "Kebbe" },
      { lga: "Kware" },
      { lga: "Rabah" },
      { lga: "Sabon Birni" },
      { lga: "Shagari" },
      { lga: "Silame" },
      { lga: "Sokoto North" },
      { lga: "Sokoto South" },
      { lga: "Tambuwal" },
      { lga: "Tangaza" },
      { lga: "Tureta" },
      { lga: "Wamako" },
      { lga: "Wurno" },
      { lga: "Yabo" },
    ],
  },
  {
    name: "Taraba",
    localGovts: [
      { lga: "Ardo Kola" },
      { lga: "Bali" },
      { lga: "Donga" },
      { lga: "Gashaka" },
      { lga: "Gassol" },
      { lga: "Ibi" },
      { lga: "Jalingo" },
      { lga: "Karim Lamido" },
      { lga: "Kumi" },
      { lga: "Lau" },
      { lga: "Sardauna" },
      { lga: "Takum" },
      { lga: "Ussa" },
      { lga: "Wukari" },
      { lga: "Yorro" },
      { lga: "Zing" },
    ],
  },
  {
    name: "Yobe",
    localGovts: [
      { lga: "Bade" },
      { lga: "Bursari" },
      { lga: "Damaturu" },
      { lga: "Fika" },
      { lga: "Fune" },
      { lga: "Geidam" },
      { lga: "Gujba" },
      { lga: "Gulani" },
      { lga: "Jakusko" },
      { lga: "Karasuwa" },
      { lga: "Machina" },
      { lga: "Nangere" },
      { lga: "Nguru" },
      { lga: "Potiskum" },
      { lga: "Tarmuwa" },
      { lga: "Yunusari" },
      { lga: "Yusufari" },
    ],
  },
  {
    name: "Zamfara",
    localGovts: [
      { lga: "Anka" },
      { lga: "Bakura" },
      { lga: "Birnin Magaji Kiyaw" },
      { lga: "Bukkuyum" },
      { lga: "Bungudu" },
      { lga: "Gummi" },
      { lga: "Gusau" },
      { lga: "Kaura Namoda" },
      { lga: "Maradun" },
      { lga: "Maru" },
      { lga: "Shinkafi" },
      { lga: "Talata Mafara" },
      { lga: "Chafe" },
      { lga: "Zurmi" },
    ],
  },
];
