import React from "react";

export const TesData = [
    {
        text: "Empowered by this platform, I save lives with each donation. Seamless connections, meaningful impact.",
        name: "Dr Adebayo",
        quote: "assets/Group 42.png",
        image: "assets/front-view-doctor-wearing-stethoscope.png",
        width: "294px",
    },
    {
        text: "Joining this platform, I found purpose in saving lives through blood donation. The seamless connection between donors and recipients is inspiring and impactful. Every donation is a step towards making a real difference",
        name: "Adeola John",
        quote: "assets/Group 42.png",
        image: "assets/horizontal-view-attractive-young-black-man-with-toothy-smile-shows-okay-gesture-says-alright-likes-somebodys-idea.png",
        cNmae: "tescard11",
        width: "599px",
    },
    {
        text: "I donate blood effortlessly and easily. Knowing I'm saving lives by simply being here, it's a privilege beyond words.",
        name: "Mr Durodola",
        quote: "assets/Group 42.png",
        image: "assets/african-american-man-wearing-round-glasses.png",
        width: "294px",
    },
    {
        text: "Empowered by this platform, I save lives with each donation. Seamless connections, meaningful impact.",
        name: "Dr Adebayo",
        quote: "assets/Group 42.png",
        image: "assets/front-view-doctor-wearing-stethoscope.png",
        width: "294px",
    },
    {
        text: "Joining this platform, I found purpose in saving lives through blood donation. The seamless connection between donors and recipients is inspiring and impactful. Every donation is a step towards making a real difference",
        name: "Adeola John",
        quote: "assets/Group 42.png",
        image: "assets/horizontal-view-attractive-young-black-man-with-toothy-smile-shows-okay-gesture-says-alright-likes-somebodys-idea.png",
        cNmae: "tescard11",
        width: "599px",
    },
    {
        text: "I donate blood effortlessly and easily. Knowing I'm saving lives by simply being here, it's a privilege beyond words.",
        name: "Mr Durodola",
        quote: "assets/Group 42.png",
        image: "assets/african-american-man-wearing-round-glasses.png",
        width: "294px",
    },
    {
        text: "Empowered by this platform, I save lives with each donation. Seamless connections, meaningful impact.",
        name: "Dr Adebayo",
        quote: "assets/Group 42.png",
        image: "assets/front-view-doctor-wearing-stethoscope.png",
        width: "294px",
    },
    {
        text: "Joining this platform, I found purpose in saving lives through blood donation. The seamless connection between donors and recipients is inspiring and impactful. Every donation is a step towards making a real difference",
        name: "Adeola John",
        quote: "assets/Group 42.png",
        image: "assets/horizontal-view-attractive-young-black-man-with-toothy-smile-shows-okay-gesture-says-alright-likes-somebodys-idea.png",
        cNmae: "tescard11",
        width: "599px",
    },
    {
        text: "I donate blood effortlessly and easily. Knowing I'm saving lives by simply being here, it's a privilege beyond words.",
        name: "Mr Durodola",
        quote: "assets/Group 42.png",
        image: "assets/african-american-man-wearing-round-glasses.png",
        width: "294px",
    },
    {
        text: "Empowered by this platform, I save lives with each donation. Seamless connections, meaningful impact.",
        name: "Dr Adebayo",
        quote: "assets/Group 42.png",
        image: "assets/front-view-doctor-wearing-stethoscope.png",
        width: "294px",
    },
    {
        text: "Joining this platform, I found purpose in saving lives through blood donation. The seamless connection between donors and recipients is inspiring and impactful. Every donation is a step towards making a real difference",
        name: "Adeola John",
        quote: "assets/Group 42.png",
        image: "assets/horizontal-view-attractive-young-black-man-with-toothy-smile-shows-okay-gesture-says-alright-likes-somebodys-idea.png",
        cNmae: "tescard11",
        width: "599px",
    },
    {
        text: "I donate blood effortlessly and easily. Knowing I'm saving lives by simply being here, it's a privilege beyond words.",
        name: "Mr Durodola",
        quote: "assets/Group 42.png",
        image: "assets/african-american-man-wearing-round-glasses.png",
        width: "294px",
    },
]